[pywikibot]
language = ar
family = genderiyya
[database]
host = 127.0.0.1
port = 3306
dbname = genderiyya_wiki
user = genderiyya_wiki
password = SuperS3cretPw0rd
ssl_disabled = True
[api]
action = http://localhost:8080/mw/api.php
rest = http://localhost:8080/mw/rest.php/localhost/v3/transform/html/to/wikitext
[other]
docker_db_container = genderwiki-migration-db-1
docker_php_container = genderwiki-migration-php-fpm-1
php_container_mw_path = /var/www/html/mw
mw_dir_path = /var/www/html/mw
[templates]
# Wikitext added to the header for current revisions of primarily-Flow pages
flow_present = {{فلو-ممكّن}}
# Wikitext added to the header for current revisions of primarily-LQT pages
lqt_present = {{ل-ك-ت-ممكّن}}
# Wikitext added to the header for old Flow revisions
flow_past = {{مراجعة-فلو-قديمة}}
# Wikitext added to the header for old LQT revisions
lqt_past = {{مراجعة-ل-ك-ت-قديمة}}
# How summaries (for non-resolved posts) are represented in Wikitext
summary = {{ملخص-فلو|$summary}}
# How resolved posts (without a summary) are represented in Wikitext
archivetop = {{بداية-أرشيف|حالة=مغلقة}}
# How resolved posts (with a summary) are represented in Wikitext
archivetop_summary = {{بداية-أرشيف|ملخص=$summary|حالة=مغلقة}}
# Added to the bottom for resolved posts, both with and without a summary
archivebottom = {{نهاية-أرشيف}}
[suppresswarnings]
# lqt_early = True
